---
- block:
  - name: Install emacs packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items: "{{ emacs_deps }}"
    tags: packages

  - name: Let's get out stuff sorted by bringing over our emacs stuff
    git: >
      repo="https://github.com/mosesrenegade/dotfiles"
      dest={{ dotfiles_root }}
      accept_hostkey=yes
      force=yes
    ignore_errors: yes

  - name: Let's symlink .emacs
    file:
      src: "{{ emacs_dotsrc }}"
      dest: "{{ emacs_dotdest }}"
      state: link
    ignore_errors: yes

  - name: Let's symlink emacs.d
    shell: $SHELL -lc "ln -sf {{ emacs_d_dotsrc }} {{ emacs_d_dotdest }}"
    ignore_errors: yes