---
- block:
  - name: Make Empire Mine
    file: >
      dest=/opt/Empire
      owner={{ ansible_env.USER }}
      group={{ ansible_env.USER }}
      recurse=yes
    become: yes
    become_user: root
    
  - name: Install Empire
    git: >
      repo={{ empire_repo }}
      dest={{ empire_dest }}
      accept_hostkey=yes
      force=yes
    become: yes
    become_user: root
    ignore_errors: yes
   