---
- block:
  - name: Install Keybase
    apt:
      deb: https://prerelease.keybase.io/keybase_amd64.deb
    become: true
    become_user: root

  - name: Install Elixir
    apt:
      deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    become: true
    become_user: root

  - name: Add different types of repositories
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items: 
      - ppa:mozillateam/thunderbird-next
      - ppa:eosrei/fonts
      - ppa:webupd8team/java
      - ppa:linrunner/tlp
      - ppa:diodon-team/stable
      - ppa:jtaylor/keepass
    become: true
    become_user: root
     
  - name: update apt
    apt: update_cache=yes cache_valid_time=86400
    become: true
    become_user: root
    changed_when: false


- block:
  - name: install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ laptop_installed_packages }}"
   
  - name: disable sshd
    systemd: 
      name: ssh
      state: stopped
      enabled: no
  become: yes
  become_user: root

# Gnome 3 configs
- block:
  - name: install packages for editing Gnome 3 settings
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - dconf-cli
    - dconf-gsettings-backend
    become: yes
    become_user: root

  # UI settings
  - name: enable minimize and maximize buttons
    command: gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"

  - name: make workspaces static
    command: gsettings set org.gnome.shell.overrides dynamic-workspaces false

  - name: set number of workspaces to four
    command: gsettings set org.gnome.desktop.wm.preferences num-workspaces 4

  - name: Set New Theme
    command: gsettings set org.gnome.desktop.interface gtk-theme "Arc-Dark"  

  - name: Set New Theme 2
    command: gsettings set org.gnome.desktop.wm.preferences theme "Arc-Dark"
    
  # Touchpad settings
  - name: modify touchpad settings
    command: gsettings set org.gnome.desktop.peripherals.touchpad {{ item.key }} {{ item.value }}
    with_items:
    # Enable two-finger scrolling
    - key: 'two-finger-scrolling-enabled'
      value: 'true'
    # Enable natural scrolling
    - key: 'natural-scroll'
      value: 'true'
    # Disable tap-to-click on touchpad
    - key: 'tap-to-click'
      value: 'false'
    # Use finger count to determine click type
    # Ex: one finger => left-click
    #     two fingers => right-click
    #     three fingers => middle-click
    - key: 'click-method'
      value: 'fingers'

  - name: Modify CTRL key settings
    command: gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:swapcaps']" 

  - debug:
      msg: "NOTE: You must logout before keyboard shortcuts will work."
  tags:
  - gnome3

- block:
  - name: Copy Autostart
    become: yes
    become_user: root
    copy:
      src: vmware-autostart
      dest: /etc/init.d
      owner: root
      group: root
      mode: 0755

  - name: Run update-rc.d
    command: update-rc.d vmware-autostart defaults
    become: yes
    become_user: root

  - name: Set Autostart to run
    become: yes
    become_user: root
    systemd:
      name: vmware-autostart
      enabled: yes
      