---
laptop_installed_packages:
- asciinema
- build-essential
- emacs
- fonts-emojione
- fonts-twemoji-svginot
- gnome-tweak-tool
- libcanberra-gtk-module
- libcurl4-openssl-dev
- libffi-dev
- libreadline-dev
- libssl-dev
- libxml2-dev
- libxslt1-dev
- net-tools
- network-manager-openvpn
- network-manager-openvpn-gnome
- openvpn
- scdaemon
- thunderbird
- tmux
- unzip
- zlib1g-dev
- zsh

zsh_users:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"

zsh_ohmy_theme: robbyrussell

zsh_ohmy_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    repo: "git://github.com/zsh-users/zsh-autosuggestions.git"

zsh_ohmy_plugins:
  - git
#  - git-flow
#  - docker
  - zsh-syntax-highlighting
  - zsh-autosuggestions

zsh_ohmy_disable_auto_update: false

#zsh_append_zshrc: ""

rbenv:
  env: user
  version: v1.0.0
  default_ruby: 2.5.1
  rubies:
   - version: 2.5.1

rbenv_clean_up: false

rbenv_repo: "https://github.com/rbenv/rbenv.git"

rbenv_plugins:
  - { name: "rbenv-vars",         repo: "https://github.com/rbenv/rbenv-vars.git",         version: "master" }
  - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
  - { name: "rbenv-gemset",       repo: "https://github.com/jf/rbenv-gemset.git",          version: "master" }
  
rbenv_root: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/.rbenv"

rbenv_users:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"

rbenv_user_profile: true

emacs_deps:
- emacs

dotfiles_root: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles"

emacs_dotsrc: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs"

emacs_dotdest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/.emacs"

emacs_d_dotsrc: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs.d"

emacs_d_dotdest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs.d"

metasploit_packages:
- postgresql
- oracle-java8-installer
- build-essential
- libreadline-dev
- libssl-dev
- libpq5
- libreadline5
- libsqlite3-dev
- libpcap-dev
- git-core
- autoconf
- pgadmin3
- curl
- zlib1g-dev
- libxml2-dev
- libxslt1-dev
- xtightvncviewer
- libyaml-dev

nmap_repo: "https://github.com/nmap/nmap.git"
nmap_compile_root: "/usr/local/src/nmap"

framework_repo: "https://github.com/rapid7/metasploit-framework"
framework_dest: "/opt/metasploit-framework"