---
laptop_installed_packages:
- arc-theme
- apt-transport-https
- asciinema
- build-essential
- curl
- conky
- diodon
- elixir
- emacs
- esl-erlang
- ethtool
- fonts-emojione
- fonts-twemoji-svginot
- freerdp2-x11 
- remmina-plugin-rdp
- gnome-tweak-tool
- gnome-clocks
- gnome-shell-extensions
- gnutls-bin
- intel-microcode
- irssi
- libaio1
- libcanberra-gtk-module
- libcurl4-openssl-dev
- libffi-dev
- libgmp-dev
- libreadline-dev
- libssl-dev
- libxml2
- libxml2-dev
- libxslt1-dev
- keypass
- net-tools
- network-manager-openvpn
- network-manager-openvpn-gnome
- openvpn
- pidgin
- python-pip
- ruby-dev
- scdaemon
- smartmontools
- software-properties-common
- thunderbird
- tlp
- tlp-rdw
- tmux
- unzip
- whois
- zlib1g-dev
- zsh

zsh_users:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"

zsh_ohmy_theme: robbyrussell

zsh_ohmy_custom_plugins:
  - name: zsh-syntax-highlighting
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
  - name: zsh-autosuggestions
    repo: "git://github.com/zsh-users/zsh-autosuggestions.git"

zsh_ohmy_plugins:
  - git
#  - git-flow
#  - docker
  - zsh-syntax-highlighting
  - zsh-autosuggestions

zsh_ohmy_disable_auto_update: false

#zsh_append_zshrc: ""

rbenv:
  env: user
  version: v1.0.0
  default_ruby: 2.5.1
  rubies:
   - version: 2.5.1

rbenv_clean_up: false

rbenv_repo: "https://github.com/rbenv/rbenv.git"

rbenv_plugins:
  - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
  - { name: "rbenv-gemset",       repo: "https://github.com/jf/rbenv-gemset.git",          version: "master" }
  
rbenv_root: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/.rbenv"

rbenv_users:
  - "{{ ansible_ssh_user|default(lookup('env', 'USER'))  }}"

rbenv_user_profile: true

emacs_deps:
- emacs

dotfiles_root: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles"

emacs_dotsrc: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs"

emacs_dotdest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/.emacs"

emacs_d_dotsrc: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs.d"

emacs_d_dotdest: "/home/{{ ansible_ssh_user|default(lookup('env', 'USER')) }}/dotfiles/.emacs.d"

metasploit_packages:
- postgresql
- oracle-java8-installer
- build-essential
- libreadline-dev
- libssl-dev
- libpq-dev
- libpq5
- libreadline5
- libsqlite3-dev
- libpcap-dev
- git-core
- autoconf
- pgadmin3
- curl
- zlib1g-dev
- libxml2-dev
- libxslt1-dev
- xtightvncviewer
- libyaml-dev

nmap_repo: "https://github.com/nmap/nmap.git"
nmap_compile_root: "/usr/local/src/nmap"

empire_repo: "https://github.com/EmpireProject/Empire"
empire_dest: "/opt/Empire"

framework_repo: "https://github.com/rapid7/metasploit-framework"
framework_dest: "/opt/metasploit-framework"

cs_installed_packages:
- evolution
- evolution-common
- evolution-ews

# Remember to add this: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# sudo apt-key fingerprint 0EBFCD88

